model:
  base_model: "meta-llama/Meta-Llama-3-8B"
  peft_model: "FinGPT/fingpt-mt_llama3-8b_lora"
  max_length: 512
  batch_size: 16
  learning_rate: 2e-5
  hidden_size: 4096
  num_attention_heads: 32
  intermediate_size: 11008
  num_hidden_layers: 32

training:
  epochs: 5
  warmup_steps: 100
  evaluation_steps: 500
  gradient_accumulation_steps: 4
  weight_decay: 0.01
  adam_epsilon: 1e-8
  max_grad_norm: 1.0
  save_steps: 1000
  logging_steps: 100

inference:
  device: "cuda"
  temperature: 0.1
  top_p: 0.95
  top_k: 50
  num_beams: 1
  max_new_tokens: 128
  do_sample: true
  no_repeat_ngram_size: 3

sentiment:
  threshold: 0.5
  positive_labels: ["bullish", "positive", "buy", "upward", "growth"]
  negative_labels: ["bearish", "negative", "sell", "downward", "decline"]
  neutral_labels: ["neutral", "stable", "unchanged"]
  confidence_threshold: 0.8
  batch_processing: true
  max_batch_size: 32

data:
  news_sources:
    - "reuters"
    - "bloomberg"
    - "wsj"
    - "marketwatch"
    - "seeking_alpha"
    - "yahoo_finance"
  update_interval: 300  # seconds
  historical_window: 30  # days
  cache_duration: 3600  # seconds
  max_headlines_per_symbol: 100

system:
  log_level: "INFO"
  cache_dir: "./cache"
  model_dir: "./models"
  output_dir: "./outputs"
  num_workers: 4
  use_multiprocessing: true
  seed: 42
  fp16: true
  memory_optimization:
    gradient_checkpointing: true
    cpu_offload: false
    attention_slicing: true

monitoring:
  enable_wandb: false
  wandb_project: "fingpt-trader"
  log_system_metrics: true
  performance_tracking: true
  error_reporting: true
  alert_thresholds:
    gpu_memory_percent: 90
    cpu_usage_percent: 80
    processing_time_seconds: 5

api:
  host: "0.0.0.0"
  port: 8000
  timeout: 30
  rate_limit: 100
  enable_cors: true
  require_auth: true