version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(levelname)s - [%(name)s:%(lineno)d] - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/fingpt_trader.log
    encoding: utf8

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    encoding: utf8

loggers:
  # Main application logger
  fingpt_trader:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

  # Development logger (more verbose)
  fingpt_trader.development:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

root:
  level: INFO
  handlers: [console]