llm:
  fingpt:
    base_model: "tiiuae/falcon-7b"
    peft_model: "FinGPT/fingpt-mt_falcon-7b_lora"
    cache:
      base_dir: "%LOCALAPPDATA%/fingpt_trader"
      model_dir: "models"
      offload_dir: "offload"
      checkpoints_dir: "checkpoints"