llm:
  fingpt:
    base_model: "tiiuae/falcon-7b"  # Full HuggingFace path
    peft_model: "FinGPT/fingpt-mt_falcon-7b_lora"
    from_remote: true
    cache:
      base_dir: "%LOCALAPPDATA%/fingpt_trader"
      model_dir: "models"
      temp_dir: "temp"