portfolio_optimization:
  risk_tolerance_levels:
    conservative: 0.3
    moderate: 0.5
    aggressive: 0.8
  
  constraints:
    min_weight: 0.0
    max_weight: 0.4
    max_sector_weight: 0.5
    min_assets: 5
  
  rebalancing:
    threshold: 0.01  # 1% threshold for trades
    schedule: "monthly"
    max_turnover: 0.2  # 20% maximum turnover

risk_management:
  risk_free_rate: 0.02
  metrics_thresholds:
    max_volatility: 0.25
    max_var_95: 0.15
    max_drawdown: 0.2
    min_sharpe: 0.5
    max_concentration: 0.4
  
  monitoring:
    frequency: "daily"
    alert_levels:
      - critical
      - high
      - medium
      - low

sentiment_integration:
  weight: 0.3  # Sentiment impact on expected returns
  lookback_period: 30  # days
  update_frequency: "daily"