# External Services Configuration
#
# Contains API credentials and service endpoints for:
# - News providers
# - ML model services
# - Fallback services
# Do not include exchange settings (moved to trading.yaml)

api:
  news:
    provider: "cryptopanic"
    key: ${CRYPTOPANIC_API_KEY}
    fallback:
      provider: "newsapi"
      key: ${NEWS_API_KEY}
    
  huggingface:
    token: ${HUGGINGFACE_TOKEN}