api:
  market_data:
    provider: "alphavantage"
    key: ${ALPHAVANTAGE_API_KEY}
    
  news:
    provider: "newsapi"
    key: ${NEWS_API_KEY}
    
  huggingface:
    token: ${HUGGINGFACE_TOKEN}
    
  crypto:
    provider: "binance"
    key: ${BINANCE_API_KEY}
    secret: ${BINANCE_SECRET_KEY}

broker:
  provider: "alpaca"
  key_id: ${ALPACA_KEY_ID}
  secret_key: ${ALPACA_SECRET_KEY}
  paper_trading: true
  base_url: "https://paper-api.alpaca.markets"