# External Services Configuration
api:
  news:
    provider: "cryptopanic"
    key: ${CRYPTOPANIC_API_KEY}
    fallback:
      provider: "newsapi"
      key: ${NEWS_API_KEY}
    
  huggingface:
    token: ${HUGGINGFACE_TOKEN}