api:
  news:
    provider: "cryptopanic"
    key: ${CRYPTOPANIC_API_KEY}
    fallback:
      provider: "newsapi"
      key: ${NEWS_API_KEY}
    
  huggingface:
    token: ${HUGGINGFACE_TOKEN}
    
  exchange:
    provider: "binance"
    key: ${BINANCE_API_KEY}
    secret: ${BINANCE_SECRET_KEY}
    test_mode: true
    base_url: "https://testnet.binance.vision"
    fallback_exchanges: ["kucoin", "huobi"]