market:
  lookback_periods:
    short: 5
    medium: 20
    long: 60
  min_confidence: 0.65

sentiment:
  model_name: 'FinGPT/fingpt-mt_falcon-7b'
  batch_size: 16

trading:
  max_position_size: 0.2
  risk_limit: 0.05
  confidence_threshold: 0.65
