exchanges:
  - name: binance
    api_key: ${BINANCE_API_KEY}
    api_secret: ${BINANCE_API_SECRET}
    test_mode: true    # Single source of truth for test/prod mode
    options:
      timeout: 30
      max_retries: 3

trading:
  pairs:
    - BTCUSDT
    - ETHUSDT
  exchanges:
    binance:
      api_key: your_api_key
      api_secret: your_api_secret

robo:
  strategy:
    risk_profile: moderate
    rebalance_threshold: 0.05
    constraints:
      min_position_size: 0.01
      max_position_size: 0.1
      max_leverage: 1.0

exchange:
  name: binance
  test_mode: true
  api_key: your_api_key
  api_secret: your_api_secret

client_profile:
  risk_score: 5
  investment_horizon: 365
  tax_rate: 0.25
  constraints:
    max_position_size: 0.1
    min_position_size: 0.01
    max_leverage: 1.0

strategies:
  tax_aware:
    enabled: true
    min_holding_period: 30
    tax_loss_threshold: -0.05

development:
  enabled: true  # Enable development mode
  test_pairs:    # Specific pairs for testing
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
  max_pairs: 10  # Or use max pairs limit instead