exchanges:
  - name: binance
    api_key: ${BINANCE_API_KEY}
    api_secret: ${BINANCE_API_SECRET}
    test_mode: true
    options:
      timeout: 30
      max_retries: 3
      use_test_net: true

trading:
  pairs:
    - BTCUSDT
    - ETHUSDT
  exchanges:
    binance:
      test_mode: true
      api_key: your_api_key
      api_secret: your_api_secret

robo:
  strategy:
    risk_profile: moderate
    rebalance_threshold: 0.05
    constraints:
      min_position_size: 0.01
      max_position_size: 0.1
      max_leverage: 1.0