# =====================================================================
# FinGPT Trader - Trading System Configuration
# =====================================================================
# Purpose: Core system configuration for the trading platform
# This file contains system-wide parameters, exchange settings, and
# global trading rules that apply across all strategies.
# 
# IMPORTANT: Strategy-specific parameters should be defined in strategies.yaml
# =====================================================================

# =====================================================================
# EXCHANGE CONFIGURATION
# =====================================================================
exchanges:
  - name: binance
    test_mode: true  # Set to false for production
    options:
      timeout: 30
      max_retries: 3
      defaultType: "spot"
      rate_limit: 
        max_requests: 10
        per_second: 1
    fallbacks:
      - name: kucoin
        test_mode: true
      - name: gate
        test_mode: true

# =====================================================================
# GLOBAL TRADING PARAMETERS
# =====================================================================
# Trading pairs that system will monitor
trading:
  # Critical settings required by validation
  pairs:  
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
  
  initial_balance: 10000.0  # Starting capital (USDT)
  loop_interval: 60  # Main trading loop interval (seconds)
  
  # Execution parameters
  execution:
    signal_threshold: 0.5  # Minimum signal strength to execute trades
    default_exchange: "binance"  # Default exchange for execution
    min_notional: 10.0        # Minimum order value in USDT
    min_quantity: 0.00001     # Minimum order quantity
    
  position_sizing:
    max_position_pct: 0.05    # Maximum position size as % of portfolio
    base_position_pct: 0.01   # Base position size as % of portfolio
    scaling_factor: 1.0       # Factor to scale position sizes
  
  # Portfolio parameters
  portfolio:
    rebalance_frequency: 86400  # Rebalance every 24 hours (seconds)
    rebalance_threshold: 0.05   # Minimum deviation to trigger rebalance (5%)
  
  # Robo advisor parameters
  robo:
    enabled: true
    fee_rate: 0.001
    min_trade_size: 15.0

# =====================================================================
# RISK MANAGEMENT
# =====================================================================
risk:
  # Portfolio risk limits
  max_drawdown: 0.1         # Maximum allowed drawdown (10%)
  position_limit: 0.2       # Maximum single position size (20%)
  concentration_limit: 0.35 # Maximum allocation to one asset class (35%)
  var_limit: 0.02           # Value-at-Risk daily limit (2%)
  
  # Leverage controls
  leverage_limit: 1.0       # Maximum allowed leverage (1x = no leverage)
  margin_minimum: 0.5       # Minimum margin requirement (50%)
  
  # Position controls
  min_position_size: 0.01   # Minimum position size (% of portfolio)
  auto_stop_loss: true      # Automatically set stop losses
  trailing_stop: false      # Use trailing stops
  
  # Emergency controls
  circuit_breaker:
    enabled: true
    daily_loss_limit: 0.05  # Halt trading after 5% daily loss
    cooldown_period: 3600   # 1-hour cooldown after circuit breaker (seconds)

# =====================================================================
# EXTERNAL CONFIGURATIONS
# =====================================================================
configs:
  model: "config/model.yaml"        # LLM model configuration
  services: "config/services.yaml"  # External services configuration
  strategies: "config/strategies.yaml"  # Trading strategies configuration

# =====================================================================
# DEVELOPMENT MODE SETTINGS
# =====================================================================
development:
  enabled: true                    # Enable development features
  debug: true                      # Enable debug logging
  test_pairs: ["BTCUSDT", "ETHUSDT", "BNBUSDT"]  # Test trading pairs
  max_pairs: 10                    # Maximum pairs in development mode
  simulated_latency: 0             # Simulated network latency (ms)
  mock_execution: true             # Use mock trade execution
  backtest:
    start_date: "2023-01-01"       # Backtest start date
    end_date: "2023-12-31"         # Backtest end date
    initial_balance: 10000.0       # Backtest starting capital