# Trading System Core Configuration

# Exchange Configuration
exchanges:
  - name: binance
    test_mode: true  # Set to false for production
    options:
      timeout: 30
      max_retries: 3
      defaultType: "spot"

# Trading Parameters
trading:
  pairs:  # Single source of truth for trading pairs
    - BTCUSDT
    - ETHUSDT
  initial_balance: 1000.0
  confidence_threshold: 0.7
  min_trade_amount: 15.0  # Increased from 1.0 to ensure above exchange minimum
  max_position_size: 0.2
  loop_interval: 60

# Risk Management
risk:
  max_drawdown: 0.1
  position_limit: 0.2
  var_limit: 0.02
  leverage_limit: 1.0
  concentration_limit: 0.35
  min_position_size: 0.01

# External Configurations
configs:
  model: "config/model.yaml"
  services: "config/services.yaml"

# Development Mode
development:
  enabled: true
  test_pairs: ["BTCUSDT", "ETHUSDT", "BNBUSDT"]
  max_pairs: 10