market_inefficiency:
  lookback_period: 20
  threshold:
    price_impact: 0.1
    bid_ask_bounce: 0.05
    order_imbalance: 2.0
    momentum: 0.02
    mean_reversion: 0.03
    overreaction: 0.04

signal_weights:
  sentiment: 0.3
  microstructure: 0.4
  psychology: 0.3

risk_management:
  max_position_size: 0.1
  stop_loss: 0.02
  take_profit: 0.05