# FinGPT Trading System Configuration
#
# This is the main configuration file for the FinGPT trading system.
# It controls both production and development environments.
#
# Environment Variables:
#   BINANCE_API_KEY: Exchange API key
#   BINANCE_SECRET_KEY: Exchange API secret
#
# Usage:
#   Production: python main.py
#   Development: python scripts/run_trader.py

# Exchange Configuration
exchange:
  name: binance                    # Exchange identifier
  api_key: ${BINANCE_API_KEY}      # From environment variable
  api_secret: ${BINANCE_SECRET_KEY} # From environment variable
  test_mode: true                  # Controls testnet/mainnet - SINGLE SOURCE OF TRUTH
  options:
    timeout: 30                    # API timeout in seconds
    max_retries: 3                 # Maximum retry attempts

# Trading Parameters
trading:
  initial_balance: 10000.0
  pairs:                            # Default trading pairs if not limited
    - "BTC/USDT"                    # Updated format
    - "ETH/USDT"                    # Updated format

# Robo-Advisory Settings
robo:
  strategy:
    risk_profile: moderate          # Risk profile: conservative, moderate, aggressive
    rebalance_threshold: 0.05       # 5% deviation triggers rebalancing
    constraints:
      min_position_size: 0.01       # Minimum position as decimal
      max_position_size: 0.1        # Maximum position as decimal
      max_leverage: 1.0             # Maximum allowed leverage

# Client Profile Settings
client_profile:
  risk_score: 5                     # Risk tolerance (1-10)
  investment_horizon: 365           # Investment horizon in days
  tax_rate: 0.25                   # Client's tax rate
  constraints:
    max_position_size: 0.1         # Maximum single position
    min_position_size: 0.01        # Minimum single position
    max_leverage: 1.0              # Maximum leverage

# Trading Strategies
strategies:
  tax_aware:
    enabled: true                  # Enable tax-aware trading
    min_holding_period: 30         # Minimum days to hold
    tax_loss_threshold: -0.05      # Trigger tax-loss harvesting at -5%

# Development Settings
development:
  enabled: true                    # Enable development mode
  test_pairs:                      # Override pairs in development
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
  max_pairs: 10                    # Limit number of pairs in development

# Note: test_mode under exchanges is the single source of truth for
# determining whether to use testnet or mainnet. This setting affects
# the entire system regardless of other configurations.